spring.application.name=ScholarTopicBoard

spring.datasource.url=jdbc:mariadb://${STBOARD_DB_HOST:localhost}:${STBOARD_DB_PORT:3306}/${STBOARD_DB_DATABSE:stboard}
spring.datasource.username=${STBOARD_DB_USERNAME:alura}
spring.datasource.password=${STBOARD_DB_PASSWORD:alura1234}
api.security.token.secret=${STBOARD_JWT_SECRET:secret}

server.error.include-stacktrace=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=/db/migration/common,/db/migration/prod

springdoc.api-docs.version=OPENAPI_3_0
