spring.datasource.url=jdbc:mariadb://${STBOARD_TEST_DB_HOST:localhost}:${STBOARD_TEST_DB_PORT:3306}/${STBOARD_TEST_DB_DATABSE:stboard_test}
spring.datasource.username=${STBOARD_TEST_DB_USERNAME:alura}
spring.datasource.password=${STBOARD_TEST_DB_PASSWORD:alura1234}
api.security.token.secret=${STBOARD_TEST_JWT_SECRET:secret}

spring.flyway.locations=/db/migration/common