
 -- Many to many Join tables
 
CREATE TABLE IF NOT EXISTS users_courses(
	user_id SMALLINT UNSIGNED NOT NULL,
	course_id SMALLINT UNSIGNED NOT NULL,
	enrollment_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	finalization_date TIMESTAMP,

	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE RESTRICT ON UPDATE CASCADE,
	
	PRIMARY KEY (user_id, course_id)
);

CREATE TABLE IF NOT EXISTS users_roles(
	user_id SMALLINT UNSIGNED NOT NULL,
	role_id TINYINT UNSIGNED NOT NULL,
	updated_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT ON UPDATE CASCADE,
	FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE RESTRICT ON UPDATE CASCADE,
	
	PRIMARY KEY (user_id, role_id)
);